preload = @HOME@/.config/hypr/wallpapers/aurelius-01-halo.jpg
preload = @HOME@/.config/hypr/wallpapers/aurelius-02-red.jpg
preload = @HOME@/.config/hypr/wallpapers/aurelius-03-face.jpg
preload = @HOME@/.config/hypr/wallpapers/aurelius-04-hands.jpg
wallpaper = eDP-1,@HOME@/.config/hypr/wallpapers/aurelius-01-halo.jpg
splash = false
